#1
SELECT sum(c.POPULATION)
FROM CITY c, COUNTRY p
WHERE c.COUNTRYCODE = p.CODE and CONTINENT = 'Asia'

#2
SELECT CITY.NAME
FROM CITY INNER JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE 
WHERE COUNTRY.CONTINENT = 'Africa'

#3
SELECT COUNTRY.CONTINENT, FLOOR(AVG(CITY.POPULATION))
FROM COUNTRY JOIN CITY ON CITY.COUNTRYCODE = COUNTRY.CODE
GROUP BY COUNTRY.CONTINENT

#4
SELECT
  CASE
    WHEN g.grade < 8 THEN null
    ELSE s.name
  END,
  g.grade,
  s.marks
FROM students AS s
JOIN grades AS g
ON s.marks >= g.min_mark AND s.marks <= g.max_mark
ORDER BY g.grade DESC, s.name ASC

#5
